#!/bin/bash

set -e

export INSTALLER_DIR="$(dirname "$(readlink -f "$0")")"

source "$INSTALLER_DIR/config.sh"

mkdir -p "$THIRD_PARTY_DIR"

source "$INSTALLER_DIR/defaults.sh"

for pkg in "$FALLBACK_DIR/package_"*.sh; do
	load_package "$(basename "$pkg")"
	if pkg_is_installed; then
		ln -sfT "$PREFIX/$PACKAGE" "$THIRD_PARTY_DIR/$NAME"
	fi
done

for pkg in "$INSTALLER_DIR/package_"*.sh; do
	load_package "$(basename "$pkg")"
	if pkg_is_installed; then
		ln -sfT "$PREFIX/$PACKAGE" "$THIRD_PARTY_DIR/$NAME"
	fi
done
