#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

cd "$BUILD_DIR"

cmake "$WORKSPACE/code" \
	-DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
	-DCMAKE_CXX_FLAGS="-Werror" \
	-DHPX_WITH_NETWORKING="$HPX_WITH_NETWORKING" \
	-DHASKELL_C_COMPILER="$BUILD_DIR/third_party/gcc/bin/gcc"

# Allow passing specific make targets to be compiled as well as everything
make -j "$NPROC" "$@"
