#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

git config url./ssd/git-mirrors/hpx.git.insteadOf              https://github.com/STEllAR-GROUP/hpx.git
git config url./ssd/git-mirrors/allscale_runtime.git.insteadOf https://github.com/allscale/allscale_runtime.git
git config url./ssd/git-mirrors/allscale_api.git.insteadOf     https://github.com/allscale/allscale_api.git
git config url./ssd/git-mirrors/insieme_base.git.insteadOf     https://github.com/insieme/insieme.git

pushd "$WORKSPACE"
git submodule update --recursive --init
popd
