#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

pushd "$WORKSPACE"
$RUNNING_ON_CI_SERVER && git submodule update --recursive --init
popd
