#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

# Remove Haskell Stack's Working Directory to simulate a clean installation.
rm -rf "$WORKSPACE/insieme/code/analysis/src/haskell/insieme-hat/.stack-work"
rm -rf "$WORKSPACE/code/compiler/src/analysis/allscale-hat/.stack-work"
