#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

# Ask git to rewrite submodule URLs so the CI jobs work 1) faster and 2) when
# the internet is broken.
#
# The script updating these mirrors on 'hudson' is at
#     ~daniel/dev/dps/git-mirror/git-mirror
# and is called by a crontab running under the user 'daniel' every 15 minutes.
if $RUNNING_ON_CI_SERVER; then
    pushd "$WORKSPACE"
    git config url./ssd/git-mirrors/hpx.git.insteadOf              https://github.com/STEllAR-GROUP/hpx.git
    git config url./ssd/git-mirrors/allscale_runtime.git.insteadOf https://github.com/allscale/allscale_runtime.git
    git config url./ssd/git-mirrors/allscale_api.git.insteadOf     https://github.com/allscale/allscale_api.git
    git config url./ssd/git-mirrors/insieme_base.git.insteadOf     https://github.com/insieme/insieme.git
    popd
fi
