#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

cd "$BUILD_DIR"

compiler/allscale_integration_tests --preprocess

insieme/driver/integration_tests --preprocess "$WORKSPACE/test/allscale"
