#!/bin/bash

set -ex

if [[ -z "${WORKSPACE+x}" ]]; then
	cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	source defaults.sh
fi

cd "$BUILD_DIR"

# AllScale.
compiler/allscale_integration_tests -w "$NPROC"

# Insieme.
#insieme/driver/integration_tests "$WORKSPACE/test/allscale"

# Cleanup.
compiler/allscale_integration_tests --postprocessing
#insieme/driver/integration_tests --postprocessing "$WORKSPACE/test/allscale"
